unit test for changes to getRefinementSoftwareName add test to that _computing.structure_refinement is now to be ignored.
Currently get two failures - multiple values and the ignoring:  _computing.structure_refinement

	[osmart@ebi-cli-003 python]$ nosetests -v unit_tests/test_entry.py                                                                    
	getCTFmethod: no ctf cif provided ... ok
	getCTFmethod: v5 cif item provided by Ezra 3iyd.v5.cif ... ok
	getCTFmethod: the old v4 cif item from 3iyc.cif ... ok
	getCTFmethod: v5 cif item _em_ctf_correction.type ... ok
	getCTFmethod: v5 cif item _em_ctf_correction.type and _em_ctf_correction.details ... ok
	getRefinementSoftwareName: 1cbs software.name only given - should be X-PLOR ... ok
	getRefinementSoftwareName: 3dcz that has list of 3 refinement programs ... FAIL
	getRefinementSoftwareName: no software names in cif should return None ... ok
	getRefinementSoftwareName: v5 change should ignore _computing.structure_refinement ... FAIL

	======================================================================
	FAIL: getRefinementSoftwareName: 3dcz that has list of 3 refinement programs
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/nfs/msd/work2/osmart/Validation/pycharm/src/python/unit_tests/test_entry.py", line 110, in test_getRefinementSoftwareName_3dcz_v5_cif
		self.assertEqual(soft_name, 'PHENIX, REFMAC5 5.2.0019, REFMAC 5.2.0019')
	AssertionError: 'PHENIX' != 'PHENIX, REFMAC5 5.2.0019, REFMAC 5.2.0019'

	======================================================================
	FAIL: getRefinementSoftwareName: v5 change should ignore _computing.structure_refinement
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/nfs/msd/work2/osmart/Validation/pycharm/src/python/unit_tests/test_entry.py", line 68, in test_getRefinementSoftwareName_v5_now_ignore_computing_dot_structure_refinement
		self.assertIsNone(soft_name)
	AssertionError: 'X-PLOR' is not None

	----------------------------------------------------------------------
	Ran 9 tests in 0.036s

	FAILED (failures=2)