Getting runmany.py working with onedep rh6 siteconfig at ebi: produce sensible error message if SITE_MMCIF_DIR not set or a no mmcif file is found.
Heavily refactored utils.getMmcifReflectionsFilepaths to try and make it readable splitting into separate methods.

Tested SITE_MMCIF_DIR not set produces:
        Traceback (most recent call last):
          File "../../../src/python/drivers/runmany.py", line 144, in <module>
            mmciffile, reflectionsfile, cspath = utils.getMmcifReflectionsFilepaths(pid, opts.steps, os.path.join(opts.rundir[pindex],"Temp"))
          File "/nfs/msd/work2/osmart/Validation/trunk/src/python/utils/utils.py", line 397, in getMmcifReflectionsFilepaths
            raise ValueError('environment variable SITE_MMCIF_DIR has not been defined')
        ValueError: environment variable SITE_MMCIF_DIR has not been defined

Tested supply bad PDB code XXXX produces:
        Traceback (most recent call last):
          File "../../../src/python/drivers/runmany.py", line 144, in <module>
            mmciffile, reflectionsfile, cspath = utils.getMmcifReflectionsFilepaths(pid, opts.steps, os.path.join(opts.rundir[pindex],"Temp"))
          File "/nfs/msd/work2/osmart/Validation/trunk/src/python/utils/utils.py", line 408, in getMmcifReflectionsFilepaths
            % (pdbid, checked_files))
        ValueError: cannot find mmcif file for pdb code "xxxx"? Have checked and none of ['/ebi/ftp/pub/databases/pdb/data/structures/all/mmCIF/xxxx.cif.gz', '/ebi/ftp/pub/databases/pdb/data/structures/obsolete/mmCIF/xx/xxxx.cif.gz'] exist

Have NOT TESTED: getting chemical shift files now done in separate method get_chemicalshifts_file
                                 or  get_mmcif_reflections_cs_file_from_pdbdep_processing() (probably no longer needed)
                                 
 For background see https://confluence.wwpdb.org/x/kgM9