add unittest test_runCommand_logging_multiple_lines that runs a command with ; and checks that in the log a new line is added after first ;
reason is to produce a readable logging.

Initially this fails as runCommand not yet updated:

    $ msdsetup ; cd /nfs/msd/work2/osmart/Validation/devel-osmart/src/python ; export PYTHONPATH=`pwd`
    $ python unit_tests/test_utils_runCommand.py
    FAIL: test_runCommand_logging_multiple_lines (__main__.TestUtilsRunCommand)
    test that command with semi-colons is logged on multiple lines
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "unit_tests/test_utils_runCommand.py", line 101, in test_runCommand_logging_multiple_lines
        self.assertIn('echo "1";\n', logging_out)   # test that first line of command is in the logging with a newline
    AssertionError: 'echo "1";\n' not found in 'EXECUTING (orc) echo "1";echo "2";echo "3" WITH CURDIR /nfs/msd/work2/osmart/Validation/devel-osmart/src/python'