Detected and raise a sensible exception if mol2 format is not supported in openbabel setup.
After change get a sensible error message in log when there is a problem. For instance:

        LOG|01-Dec-2016 17:43:23|INFO    ===============START VALIDSTEP mogul current dir: /tmp/validator-tst-MkafG8YTZz/DE/1DET
        LOG|01-Dec-2016 17:43:23|WARNING    Element mapping keys not found, non-hydrogens might get filtered out: DI C4 N3 HN3
        LOG|01-Dec-2016 17:43:23|WARNING    Element mapping keys not found, non-hydrogens might get filtered out: DI HN3 N3 C2
        LOG|01-Dec-2016 17:43:23|INFO    Ignoring hetgroup ('1DET', '1', 'A', '107', '?', 'NA', '.') because it is mono-atomic.
        LOG|01-Dec-2016 17:43:23|INFO    Processing hetgroup ('1DET', '1', 'A', '58', '?', 'CGA', '.') num-modelled-atoms 13
        ==============================
        *** Open Babel Warning  in Init
          Cannot open element.txt defaulting to compiled data.
        LOG|01-Dec-2016 17:43:23|ERROR    ValidationWrapper for step mogul yielded exception! There is a problem with the openbabel installation: mol2 format not supported? Traceback (most recent call last):
          File "/nfs/msd/work2/osmart/Validation/trunk/src/python/run_validator/stepwrapper.py", line 200, in run
            RunMogul(self.entry, props, self.mmciffile, self.pdbfile, self.rundir_step).run()
          File "/nfs/msd/work2/osmart/Validation/trunk/src/python/wrappers/mogul.py", line 152, in run
            s.runMogul(subgr)
          File "/nfs/msd/work2/osmart/Validation/trunk/src/python/wrappers/mogul.py", line 76, in runMogul
            s.write_mol2(subgr, mol2fn)
          File "/nfs/msd/work2/osmart/Validation/trunk/src/python/wrappers/mogul.py", line 130, in write_mol2
            chemgroup.writeMol2file(subgr, mol2_file_name)
          File "/nfs/msd/work2/osmart/Validation/trunk/src/python/pdboi/pdbents/chemicalgroup.py", line 225, in writeMol2file
            raise RuntimeError("There is a problem with the openbabel installation: mol2 format not supported?")
        RuntimeError: There is a problem with the openbabel installation: mol2 format not supported?

See http://confluence.wwpdb.org/x/ZQM9