Little test script for Entry methods .getRevisionDate() and .getDepositionDate() to check how they handle  mmcif file with _database_PDB_rev missing. Written to sort
DAOTHER-831 Xtriage and Mogul fail if database_PDB_rev category is missing

In isolation from rest of code.

Output of script before fix:

	first test a valid cif file then one that lacks database_PDB_rev category
	mmcifFile = /nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../../../tests/cases/004/IN.cif
	Revision number:  2
	Revision Date:  2009-02-24
	Deposition Date:  1996-02-20
	mmcifFile = /nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../../../tests/cases/008/IN.cif
	Revision number:  unknown
	Revision Date:  got exception! Details: 
	Traceback (most recent call last):
	  File "python/jiffys/test-Entry.getDates.py", line 34, in <module>
		print entry.getRevisionDate()
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbents/entry.py", line 68, in getRevisionDate
		for fulldate in s.dc.getCategory("database_PDB_rev","date","iter") :
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbdata/mmcifapiconnector.py", line 43, in getCategory
		except : raise MMcifCategoryNotFoundException("No category found: " + cat)
	MMcifCategoryNotFoundException: No category found: database_PDB_rev

	continuing after exception
	Deposition Date:  got exception! Details: 
	Traceback (most recent call last):
	  File "python/jiffys/test-Entry.getDates.py", line 42, in <module>
		print entry.getDepositionDate();
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbents/entry.py", line 76, in getDepositionDate
		for fulldate in s.dc.getCategory("database_PDB_rev","date_original","iter") :
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbdata/mmcifapiconnector.py", line 43, in getCategory
		except : raise MMcifCategoryNotFoundException("No category found: " + cat)
	MMcifCategoryNotFoundException: No category found: database_PDB_rev

	continuing after exception

Shows that: 
1. dates and revision number correctly got from valid file
2. for the file lacking _database_PDB_rev the same exceptions as DAOTHER-831 are raised.