Add unit tests for the utils.runCommand method (devel-osmart branch). N.B. currently two tests fail because runCommand does not capture any output to stderr instead always returning empty list.
Testing functioning of the method prior to writing docstring.

How to run all tests from command line:
***************************************

Setup:
    msdsetup
    cd /nfs/msd/work2/osmart/Validation/devel-osmart/src/python
    export PYTHONPATH=`pwd` 

All tests:
    python unit_tests/test_utils_runCommand.py


Single test:
   python unit_tests/test_utils_runCommand.py  TestUtilsRunCommand.test_runCommand_ls_non_existent_file_stderr_message_is_captured

Output of all tests showing failures 
************************************

	$ python unit_tests/test_utils_runCommand.py
	This message goes to stderr
	F.....****exitStatus of - ls /../../this_file-cannot_exist >& /dev/null - was unacceptable**** 512 [0]
	.ls: cannot access /../../this_file-cannot_exist: No such file or directory
	****exitStatus of - ls /../../this_file-cannot_exist - was unacceptable**** 512 [0]
	F****exitStatus of - ls /../../this_file-cannot_exist >& /dev/null - was unacceptable**** 512 [0]
	.****exitStatus of - echo - was unacceptable**** 0 [1]
	STDOUT 
	.
	======================================================================
	FAIL: test_echo_to_stderr_is_captured (__main__.TestUtilsRunCommand)
	run a echo command redirected to stderr and check string is captured and returned.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "unit_tests/test_utils_runCommand.py", line 74, in test_echo_to_stderr_is_captured
		self.assertEqual(stderr, ['This message goes to stderr'])
	AssertionError: Lists differ: [] != ['This message goes to stderr'...

	Second list contains 1 additional elements.
	First extra element 0:
	This message goes to stderr

	- []
	+ ['This message goes to stderr']

	======================================================================
	FAIL: test_runCommand_ls_non_existent_file_stderr_message_is_captured (__main__.TestUtilsRunCommand)
	run command listing file that cannot exist. Check that stderr not returned as empty list.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "unit_tests/test_utils_runCommand.py", line 64, in test_runCommand_ls_non_existent_file_stderr_message_is_captured
		self.assertNotEqual(stderr, [])
	AssertionError: [] == []

	----------------------------------------------------------------------
	Ran 10 tests in 0.098s

See https://www.ebi.ac.uk/seqdb/confluence/x/MahfAg