validation_xml_reader.py: initial (rough) version. * idea parses validation xml file into dictionary or lists of dictionaries * features want to get a user dump of all the contents to help in debugging * want comparison methods to easily compare two xml files - what fields are different?
* initial unit test deliberately fails causing the  log:
[osmart@ebi-001 python]$ PYTHONPATH=`pwd`
        [osmart@ebi-001 python]$ python unit_tests/test_validation_xml_reader.py 
        1cbs short dump from str:
        <Entry> tag dictionary:
        {'B_factor_type': 'FULL',
         'CCP4version': '6.5.0',
         'DCC_R': '0.18',
         'DCC_Rfree': '0.19',
         'DCC_refinement_program': 'CNS',
         'DataAnisotropy': '0.434',
         'DataCompleteness': '90.54',
         'EDS_R': '0.18',
         'EDS_resolution': '1.80',
         'EDS_resolution_low': '14.93',
         'Fo_Fc_correlation': '0.956',
         'IoverSigma': '3.77(1.79A)',
         'PDB-R': '0.20',
         'PDB-Rfree': '0.24',
         'PDB-deposition-date': '1994-09-28',
         'PDB-resolution': '1.80',
         'PDB-resolution-low': '8.00',
         'PDB-revision-date': '2009-02-24',
         'PDB-revision-number': '3',
         'RefmacVersion': '5.8.0135',
         'RestypesNotcheckedForBondAngleGeometry': 'REA',
         'TransNCS': 'The largest off-origin peak in the Patterson function is 9.26% of the height of the origin peak. No significant pseudotranslation is detected.',
         'TwinFraction': 'k,h,-l:0.027',
         'TwinL': '0.515',
         'TwinL2': '0.357',
         'WilsonBaniso': '[16.802,17.606,11.032,0.000,0.000,0.000]',
         'WilsonBestimate': '14.785',
         'XMLcreationDate': 'Jan 31, 2016 -- 06:45 PM GMT',
         'absolute-percentile-DCC_Rfree': '91.5',
         'absolute-percentile-clashscore': '74.3',
         'absolute-percentile-percent-RSRZ-outliers': '100.0',
         'absolute-percentile-percent-rama-outliers': '100.0',
         'absolute-percentile-percent-rota-outliers': '56.6',
         'acentric_outliers': '1',
         'angles_rmsz': '0.71',
         'attemptedValidationSteps': 'mogul,xtriage,molprobity,validation-pack,eds,coreclust,chemicalshifts,percentiles,writexml,writepdf',
         'babinet_b': '144.090',
         'babinet_k': '0.156',
         'bonds_rmsz': '0.47',
         'bulk_solvent_b': '72.837',
         'bulk_solvent_k': '0.400',
         'centric_outliers': '0',
         'clashscore': '4.01',
         'cyrange_error': ' Less than two structures selected.',
         'cyrange_version': 'Kirchner et al. (2012)',
         'high-resol-relative-percentile-DCC_Rfree': '1.8',
         'high-resol-relative-percentile-clashscore': '1.8',
         'high-resol-relative-percentile-percent-RSRZ-outliers': '1.8',
         'high-resol-relative-percentile-percent-rama-outliers': '1.8',
         'high-resol-relative-percentile-percent-rota-outliers': '1.8',
         'low-resol-relative-percentile-DCC_Rfree': '1.8',
         'low-resol-relative-percentile-clashscore': '1.8',
         'low-resol-relative-percentile-percent-RSRZ-outliers': '1.8',
         'low-resol-relative-percentile-percent-rama-outliers': '1.8',
         'low-resol-relative-percentile-percent-rota-outliers': '1.8',
         'nmr_models_consistency_flag': 'True',
         'nmrclust_error': 'Wrapper check: not enough residues in core to run NmrClust',
         'nmrclust_version': 'Kelley et al. (1996)',
         'num-H-reduce': '1133',
         'num-free-reflections': '1479',
         'numMillerIndices': '14678',
         'numPDBids-absolute-percentile-DCC_Rfree': '91344',
         'numPDBids-absolute-percentile-clashscore': '102246',
         'numPDBids-absolute-percentile-percent-RSRZ-outliers': '91569',
         'numPDBids-absolute-percentile-percent-rama-outliers': '100387',
         'numPDBids-absolute-percentile-percent-rota-outliers': '100360',
         'numPDBids-relative-percentile-DCC_Rfree': '4533',
         'numPDBids-relative-percentile-clashscore': '5383',
         'numPDBids-relative-percentile-percent-RSRZ-outliers': '4547',
         'numPDBids-relative-percentile-percent-rama-outliers': '5320',
         'numPDBids-relative-percentile-percent-rota-outliers': '5319',
         'num_angles_rmsz': '1491',
         'num_bonds_rmsz': '1107',
         'panav_version': 'Wang et al. (2010)',
         'pdbid': '1CBS',
         'percent-RSRZ-outliers': '0.00',
         'percent-free-reflections': '10.17',
         'percent-rama-outliers': '0.00',
         'percent-rota-outliers': '2.44',
         'percentilebins': 'all,1.8,xray',
         'protein-DNA-RNA-entities': '1',
         'rci_version': 'v_1n_11_5_13_A (Berjanski et al., 2005)',
         'relative-percentile-DCC_Rfree': '93.2',
         'relative-percentile-clashscore': '66.8',
         'relative-percentile-percent-RSRZ-outliers': '100.0',
         'relative-percentile-percent-rama-outliers': '100.0',
         'relative-percentile-percent-rota-outliers': '40.8',
         'shiftchecker_version': 'rb-20026688',
         'xtriage_input_columns': 'F_meas_au,F_meas_sigma_au'}
        number of <ModelledSubgroup>'s parsed is 238
        number of <ModelledEntityInstance>'s parsed is 1
        number of <program>'s parsed is 9
        
        F
        ======================================================================
        FAIL: test_1cbs_entry_stuff (__main__.TestValidationXMLReader)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "unit_tests/test_validation_xml_reader.py", line 33, in test_1cbs_entry_stuff
            self.assertEqual(xml_reader_1cbs.entry['pdbid'],'1CBS + deliberate fail!')
        AssertionError: '1CBS' != '1CBS + deliberate fail!'

 See https://confluence.wwpdb.org/x/NwJG