add unit test for change to getRefinementSoftwareName - currently fails.
	[osmart@ebi-cli-003 python]$ nosetests -v unit_tests/test_entry.py
	getCTFmethod: no ctf cif provided ... ok
	getCTFmethod: v5 cif item provided by Ezra 3iyd.v5.cif ... ok
	getCTFmethod: the old v4 cif item from 3iyc.cif ... ok
	getCTFmethod: v5 cif item _em_ctf_correction.type ... ok
	getCTFmethod: v5 cif item _em_ctf_correction.type and _em_ctf_correction.details ... ok
	getRefinementSoftwareName: 1cbs just the software item ... ok
	getRefinementSoftwareName: 3dcz that has list of 3 refinement programs ... FAIL

	======================================================================
	FAIL: getRefinementSoftwareName: 3dcz that has list of 3 refinement programs
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/nfs/msd/work2/osmart/Validation/pycharm/src/python/unit_tests/test_entry.py", line 93, in test_getRefinementSoftwareName_3dcz_v5_cif
		self.assertEqual(soft_name, 'PHENIX, REFMAC5 5.2.0019, REFMAC 5.2.0019')
	AssertionError: 'PHENIX' != 'PHENIX, REFMAC5 5.2.0019, REFMAC 5.2.0019'