merging trunk revision 27256 through 27086 into rb-200
------------------------------------------------------------------------
r27256 | osmart | 2016-04-13 16:26:51 +0100 (Wed, 13 Apr 2016) | 6 lines

Test script results now that DAOTHER-831 fixed.

see: 
https://www.ebi.ac.uk/seqdb/confluence/x/LotfAg
http://tracking.wwpdb.org/jira/browse/DAOTHER-831

------------------------------------------------------------------------
r27255 | osmart | 2016-04-13 16:22:09 +0100 (Wed, 13 Apr 2016) | 7 lines

tests/cases/008 results now show that "DAOTHER-831 Xtriage and Mogul fail if
database_PDB_rev category is missing" is fixed

see: 
https://www.ebi.ac.uk/seqdb/confluence/x/LotfAg
http://tracking.wwpdb.org/jira/browse/DAOTHER-831

------------------------------------------------------------------------
r27254 | osmart | 2016-04-13 16:15:28 +0100 (Wed, 13 Apr 2016) | 4 lines

tests/cases/003 NMR test case commit updated results that show NMR report xml
schema validation problem now fixed by r27251.


------------------------------------------------------------------------
r27253 | osmart | 2016-04-13 16:00:35 +0100 (Wed, 13 Apr 2016) | 10 lines

Bug fix for mmcif input file with _database_PDB_rev category missing.  Deals
with DAOTHER-831: "Xtriage and Mogul fail if database_PDB_rev category is
missing"

Tested by tests/cases/008 and python/jiffys/test-Entry.getDates.py

See:
https://www.ebi.ac.uk/seqdb/confluence/x/LotfAg
http://tracking.wwpdb.org/jira/browse/DAOTHER-831

------------------------------------------------------------------------
r27252 | osmart | 2016-04-13 15:32:53 +0100 (Wed, 13 Apr 2016) | 2 lines

cp_validator_results_to_ftp_dir_structure_and_gz.py: (jiffy script) get rid of sed invocation to correct (badly) the xml schema location. 

------------------------------------------------------------------------
r27251 | aleks | 2016-04-13 13:12:46 +0100 (Wed, 13 Apr 2016) | 11 lines


1. JIRA DAOTHER-857
Changes to xmlwriter.py 
Make sure that chemical shift referencing uncertainty is always decimal. It is now set to 0.0 if not calculated.
2. Change to pdfwriternmr.py 
Better wording in "Ensemble composition" section for cases when entry either does not contain protein or has too few models in the ensemble for Cyrange and NMRClust to run. (No JIRA created). 





------------------------------------------------------------------------
r27250 | osmart | 2016-04-12 17:35:18 +0100 (Tue, 12 Apr 2016) | 44 lines

Little test script for Entry methods .getRevisionDate() and .getDepositionDate() to check
how they handle  mmcif file with _database_PDB_rev missing. Written to sort

DAOTHER-831 Xtriage and Mogul fail if database_PDB_rev category is missing

In isolation from rest of code.

Output of script before fix:

	first test a valid cif file then one that lacks database_PDB_rev category
	mmcifFile = /nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../../../tests/cases/004/IN.cif
	Revision number:  2
	Revision Date:  2009-02-24
	Deposition Date:  1996-02-20
	mmcifFile = /nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../../../tests/cases/008/IN.cif
	Revision number:  unknown
	Revision Date:  got exception! Details: 
	Traceback (most recent call last):
	  File "python/jiffys/test-Entry.getDates.py", line 34, in <module>
		print entry.getRevisionDate()
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbents/entry.py", line 68, in getRevisionDate
		for fulldate in s.dc.getCategory("database_PDB_rev","date","iter") :
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbdata/mmcifapiconnector.py", line 43, in getCategory
		except : raise MMcifCategoryNotFoundException("No category found: " + cat)
	MMcifCategoryNotFoundException: No category found: database_PDB_rev

	continuing after exception
	Deposition Date:  got exception! Details: 
	Traceback (most recent call last):
	  File "python/jiffys/test-Entry.getDates.py", line 42, in <module>
		print entry.getDepositionDate();
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbents/entry.py", line 76, in getDepositionDate
		for fulldate in s.dc.getCategory("database_PDB_rev","date_original","iter") :
	  File "/nfs/msd/work2/osmart/Validation/trunk/src/python/jiffys/../pdboi/pdbdata/mmcifapiconnector.py", line 43, in getCategory
		except : raise MMcifCategoryNotFoundException("No category found: " + cat)
	MMcifCategoryNotFoundException: No category found: database_PDB_rev

	continuing after exception

Shows that: 
1. dates and revision number correctly got from valid file
2. for the file lacking _database_PDB_rev the same exceptions as DAOTHER-831 are raised.


------------------------------------------------------------------------
r27249 | osmart | 2016-04-12 11:31:45 +0100 (Tue, 12 Apr 2016) | 12 lines

tests/cases/008 test commit output files demonstrates the DAOTHER-831 problem
"During annotation, Xtriage and Mogul fail if database_PDB_rev category is missing."

The PDF output  008/out.pdf has:
	* Mogul NOT EXECUTED
	* Xtriage NOT EXECUTED

The log file 008/out-log.txt shows MMcifCategoryNotFoundException Exceptions thrown in the xtriage
and Mogul - stages just because these are the first two steps run

see https://www.ebi.ac.uk/seqdb/confluence/x/LotfAg for more details

------------------------------------------------------------------------
r27248 | osmart | 2016-04-12 11:25:16 +0100 (Tue, 12 Apr 2016) | 7 lines

tests/cases/008 test created to deal with DAOTHER-831 "During annotation, Xtriage and Mogul fail if database_PDB_rev category is missing."
comment out _database_PDB_rev lines from 004 (1det)

Forgot to commit IN_ANNOTATION in previous commit.

see https://www.ebi.ac.uk/seqdb/confluence/x/LotfAg

------------------------------------------------------------------------
r27247 | osmart | 2016-04-12 11:05:06 +0100 (Tue, 12 Apr 2016) | 7 lines

tests/cases/008 comment out _database_PDB_rev lines from 004 (1det)
test created to deal with DAOTHER-831 "During annotation, Xtriage and Mogul fail if database_PDB_rev category is missing."

This commit just the test files.

see https://www.ebi.ac.uk/seqdb/confluence/x/LotfAg

------------------------------------------------------------------------
r27241 | osmart | 2016-04-09 18:34:11 +0100 (Sat, 09 Apr 2016) | 6 lines

Correct bug: EM Validation report PDF front page lists program "Calpha geometry
: ......." even when there is the trace atom geometry is turned off.

See EBI confluence page: 
https://www.ebi.ac.uk/seqdb/confluence/x/iZFfAg

------------------------------------------------------------------------
r27240 | osmart | 2016-04-08 15:49:22 +0100 (Fri, 08 Apr 2016) | 4 lines

003 NMR results following JMB's fix to EBI problem following D&A deployment changes.

See https://www.ebi.ac.uk/seqdb/confluence/display/~osmart/NMR+report+generation+problem

------------------------------------------------------------------------
r27206 | osmart | 2016-04-06 16:25:52 +0100 (Wed, 06 Apr 2016) | 12 lines

Sort bug where deposited _pdbx_reflns_twin information is wrongly reported in
the Data and Refinement statistics table row "Estimated twinning fraction" as
well as in the "Reported twinning fraction row.

Correction made following support request from Alex Wlodawer. 

Code tested on 5b37,  tests/cases/004 (1det) and 4cha before deposition.

For further see PDB confluence page: https://www.ebi.ac.uk/seqdb/confluence/x/PoNfAg

Should solve http://tracking.wwpdb.org/jira/browse/VALIDPIPE-74

------------------------------------------------------------------------
r27123 | aleks | 2016-03-17 10:28:23 +0000 (Thu, 17 Mar 2016) | 18 lines

Reason: 
NMR validation reports flags H1,H2,H3 atoms as missing from chemcomp definition for N-terminal non-standard residues. This is relevant only for IN_ANNOTATION == y mode.

Solution:
1) Added two functions in src/python/pdboi/pdbents/entity.py to fetch the pdbx_poly_seq_scheme table form the mmCIF.
2) modified getEntryData() function in src/python/wrappers/chemicalShifts.py to include label_seq_id in the atom dictionary at residue level (s.entryData). Moved the atom dictionary per residue a level down, so that teh full dictionary structre is as follows:
s.entryData = {
	<chain_id>: {
		<author defined residue name and number tuple>: {
			'label_seq_id': <atom_site.label_seq_id for residues in atom_site or pdbx_poly_seq_scheme.seq_id for unmodelled residues,
			'atoms': {}
		}
	}
3) Correspondingly modified instances where s.entryData is used and added a check for label_seq_id == 1 to decide if a residue is N-terminalor not. Add ['H1', 'H2', 'H3'] to the list of chemcomp atoms.