Try to deal with the wwpdb server error:
  File "/wwpdb_da/da_top/wwpdb_da_test_c6/source/python/wwpdb/apps/validation/src/python/utils/utils.py", line 659, in getCCP4setupCommand
    if not os.path.isfile(ccp4setup) :
	UnboundLocalError: local variable 'ccp4setup' referenced before assignment

Error caused by whitespace rather than tabs in getCCP4setupCommand? Replace whitespace with tabs.

See https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=35673143